name: Telegram Notification Workflow

on:
  workflow_call:
    inputs:
      chat_id:
        description: "Telegram chat ID"
        required: true
        type: string
      template:
        description: "Message template markdown"
        required: true
        type: string
    secrets:
      bot_token:
        description: "Telegram bot token"
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'themakers/telegram-action'
          ref: 'master'
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: go run actions/telegram-push/main.go --bot-token=${{ secrets.bot_token }} --chat-id=${{ inputs.chat_id }}
        env:
          MESSAGE_TEMPLATE: ${{ inputs.template }}

          INPUTS_CONTEXT_JSON:   ${{ toJSON(inputs) }}
          GITHUB_CONTEXT_JSON:   ${{ toJSON(github) }}
          JOB_CONTEXT_JSON:      ${{ toJSON(job) }}
          STEPS_CONTEXT_JSON:    ${{ toJSON(steps) }}
          RUNNER_CONTEXT_JSON:   ${{ toJSON(runner) }}
          STRATEGY_CONTEXT_JSON: ${{ toJSON(strategy) }}
          MATRIX_CONTEXT_JSON:   ${{ toJSON(matrix) }}
