name: Telegram Notification Workflow

on:
  workflow_call:
    inputs:
      chat_id:
        description: "Telegram chat ID"
        required: true
        type: string
    secrets:
      bot_token:
        description: "Telegram bot token"
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - run: go run actions/telegram-push/main.go --bot-token=${{ secrets.bot_token }}
